#define IDS_LBL_POLICY_SETTING_ENABLED			1000
#define IDS_LBL_POLICY_SETTING_DISABLED			1001
#define IDS_LBL_POLICY_SETTING_NOT_CONFIGURED	1002
#define IDS_LBL_POLICY_SETTING_NOT_APPLICABLE	1003

#define IDS_LBL_POLICY_DESCRIPTION_ENABLED			1100
#define IDS_LBL_POLICY_DESCRIPTION_DISABLED			1101
#define IDS_LBL_POLICY_DESCRIPTION_NOT_APPLICABLE	1102

#define IDS_BTN_TOGGLE_ENABLED			1200
#define IDS_BTN_TOGGLE_DISABLED			1201
#define IDS_BTN_TOGGLE_NOT_APPLICABLE	1202

#define IDS_ERROR_SET_POLICY			1300
#define IDS_ERROR_NEED_VISTA_OR_GREAT	1301

#define IDS_VERSION	1400
